### ISSUE TITLE
Live Demo page fails to open

### ISSUE THREAD

**Issue by tony19** [mfuu/react-virtual-drag-list#7]
The live demo page crashes on open:

```
react-dom.development.js:26972 Uncaught ReferenceError: VirtualDragList is not defined
    at VirtualList (<anonymous>:165:7)
    at renderWithHooks (react-dom.development.js:15496:20)
    at mountIndeterminateComponent (react-dom.development.js:20113:15)
    at beginWork (react-dom.development.js:21636:18)
    at beginWork$1 (react-dom.development.js:27475:16)
    at performUnitOfWork (react-dom.development.js:26606:14)
    at workLoopSync (react-dom.development.js:26515:7)
    at renderRootSync (react-dom.development.js:26483:9)
    at recoverFromConcurrentError (react-dom.development.js:25899:22)
    at performConcurrentWorkOnRoot (react-dom.development.js:25799:24)
```

**Comment by mfuu** [comment]
Fixed, document generation method will be replaced in the future.
